config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index", :as => "welcome"

  resources :concerts
  #Auth0 routes
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  resources :paperclip_images
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  get '/about-us', to: "welcome#about_us", as: "about_us"
  delete '/sessions', to: 'sessions#destroy', as: 'logout'

end

app/models/paperclip_image.rb
class PaperclipImage < ApplicationRecord
	belongs_to :concert

	has_attached_file :asset, styles: { 
		medium: '300x300>', 
		small: '140X140>',
		thumb: '64x64!' 
	}


  	validates_attachment_content_type :asset, content_type: /\Aimage\/.*\Z/

end

app/controllers/paperclip_images_controller.rb
class PaperclipImagesController < ApplicationController
  before_action :set_paperclip_image, only: [:show, :edit, :update, :destroy]
  layout 'user'

  # GET /paperclip_images
  # GET /paperclip_images.json
  def index
    @paperclip_images = PaperclipImage.all
  end

  # GET /paperclip_images/1
  # GET /paperclip_images/1.json
  def show
  end

  # GET /paperclip_images/new
  def new
    @paperclip_image = PaperclipImage.new
  end

  # GET /paperclip_images/1/edit
  def edit
  end

  # POST /paperclip_images
  # POST /paperclip_images.json
  def create

    @paperclip_image = PaperclipImage.new(paperclip_image_params)
    respond_to do |format|
      if @paperclip_image.save
        format.html { redirect_to @paperclip_image, notice: 'Paperclip image was successfully created.' }
        format.json { render :show, status: :created, location: @paperclip_image }
      else
        format.html { render :new }
        format.json { render json: @paperclip_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paperclip_images/1
  # PATCH/PUT /paperclip_images/1.json
  def update
    respond_to do |format|
      # Need to come back to this, if no image is updated save does not work

      if @paperclip_image.update(paperclip_image_params)
        format.html { redirect_to @paperclip_image, notice: 'Paperclip image was successfully updated.' }
        format.json { render :show, status: :ok, location: @paperclip_image }
      else
        format.html { render :edit }
        format.json { render json: @paperclip_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paperclip_images/1
  # DELETE /paperclip_images/1.json
  def destroy
    @paperclip_image.destroy
    respond_to do |format|
      format.html { redirect_to paperclip_images_url, notice: 'Paperclip image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paperclip_image
      @paperclip_image = PaperclipImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paperclip_image_params
      params.require(:paperclip_image).permit(:asset)
      # params.fetch(:paperclip_image, {})
    end
end

app/helpers/paperclip_images_helper.rb
module PaperclipImagesHelper
end

app/views/paperclip_images/_form.html.erb
<%= form_for @paperclip_image,  html: { multipart: true } do |f| %>
  <% if @paperclip_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paperclip_image.errors.count, "error") %> prohibited this @paperclip_image from being saved:</h2>

      <ul>
      <% @paperclip_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group"> 
    <%= f.label :asset %>
    <%= f.file_field :asset, html: { class: 'form-control'} %>
    <% if f.object.asset? %>
    <br />
    <%= image_tag(f.object.asset.url(:small)) %><br />
    <em>Currently uploaded image</em> 
  <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit "Save", class:" btn btn-primary" %>
  </div>
<% end %>

app/views/paperclip_images/edit.html.erb
<h1>Editing Paperclip Image</h1>

<%= render 'form', paperclip_image: @paperclip_image %>

<%= link_to 'Show', @paperclip_image %> |
<%= link_to 'Back', paperclip_images_path %>

app/views/paperclip_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paperclip Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paperclip_images.each do |paperclip_image| %>
      <tr>
        <td><%= link_to image_tag(paperclip_image.asset.url(:thumb), class: "img-thumbnail"), paperclip_image %></td>
        <td><%= link_to 'Edit', edit_paperclip_image_path(paperclip_image) %></td>
        <td><%= link_to 'Destroy', paperclip_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paperclip Image', new_paperclip_image_path %>

app/views/paperclip_images/new.html.erb
<h1>New Paperclip Image</h1>

<%= render 'form', paperclip_image: @paperclip_image %>

<%= link_to 'Back', paperclip_images_path %>

app/views/paperclip_images/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag @paperclip_image.asset.url(:medium), class: "img-thumbnail" %>


<%= link_to 'Edit', edit_paperclip_image_path(@paperclip_image) %> |
<%= link_to 'Back', paperclip_images_path %>