config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index", :as => "welcome"

  resources :concerts
  #Auth0 routes
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  resources :paperclip_images
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  get '/about-us', to: "welcome#about_us", as: "about_us"
  delete '/sessions', to: 'sessions#destroy', as: 'logout'

end

app/models/concert.rb
class Concert < ApplicationRecord
	belongs_to :user
	has_many :paperclip_images
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]
  layout "user"

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show

  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @paperclip_image = PaperclipImage.new
    # @concert.paperclip_image << @paperclip_image
    puts session[:user_id]
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create


    @concert = Concert.new(concert_params)
    @paperclip_image = PaperclipImage.new(paperclip_image_params)
    @paperclip_image.concert = @concert

    # Need to push the image to S3 now.


    respond_to do |format|
      if @concert.save && @paperclip_image.save
        format.html { redirect_to user_path(concert_params[:user_id]), notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      #params.fetch(:concert, {})
      params.require(:concert).permit(:band, :venue, :date, :notes, :user_id)
    end

    def paperclip_image_params
      params.require(:paperclip_image).permit(:asset)
      # params.fetch(:paperclip_image, {})
    end

end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_form.html.erb
<div class="container">

  <%= form_for(concert, html: { multipart: true })   do |f| %>

    <div class="field">
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>
    <div class="field">
      <%= f.label :band %>
      <%= f.text_field :band %>
    </div>
    <div class="field">
      <%= f.label :venue%>
      <%= f.text_field :venue %>
    </div>
    <div class="field">
      <%= f.label :notes %>
      <%= f.text_area :notes %>
    </div>
     <div class="field">
      <%= f.text_field :user_id, :value => session[:user_id], :type=>"hidden" %>
    </div>

      <%= fields_for @paperclip_image do |image| %>
        <div class="form-group">
            <%= image.label :asset %>
            <%= image.file_field :asset, html: { class: 'form-control'} %>
          <% if image.object.asset? %>
          <br />
            <%= image_tag(image.object.asset.url(:small)) %><br />
          <em>Currently uploaded image</em>
        <%end%>
        </div>
      <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

</div>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>


<%= render 'form', concert: @concert %>


<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>